; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:hifive1-revb]
platform = sifive
board = hifive1-revb
framework = freedom-e-sdk
; Exclude the Lab 1 sources when building the blink app
build_src_filter = +<*> -<lab1/> -<lab1/**>
; Optional: uncomment to force onboard J-Link
; upload_protocol = jlink

[env:lab1-uart]
platform = sifive
board = hifive1-revb
framework = freedom-e-sdk
; Build only the Lab 1 (UART) sources
build_src_filter = -<*> +<lab1/**>
monitor_speed = 115200
; upload_protocol = jlink

[env:lab1-asm]
platform = sifive
board = hifive1-revb
framework = freedom-e-sdk
; Build only the Lab 1 Part 1 assembly demo: C main + asm_main.S
build_src_filter = -<*> +<lab1_asm/**> +<lab1/asm_main.S>
